### ISSUE TITLE
Some weird parts in the code

### ISSUE THREAD

**Issue by bbuing9** [andyzoujm/autocast#1]
Hi, All. First, thanks for the great work and the efforts to make it open-source!

Now, I'm trying to reproduce the results with the provided code. 

While I was reviewing and running each file step-by-step, I observed some weird lines as denoted below (3rd block in `./autocast_experiments/data/process.ipynb`).

```
negated_questions = json.load(open(f'negated_tf_questions.json'))
autocast_questions = json.load(open(f'autocast_questions.json'))
qid_to_question = {q['id']: q for q in autocast_questions}
qid_to_negation = {q['id']: q for q in negated_questions}
all_questions = []
for q in data:
    q['qtype'] = qid_to_question[q['question_id']]['qtype']
    if q['question_id'] in qid_to_negation:
        negated_q = copy.deepcopy(q)
        negated_q['question'] = qid_to_negation[q['question_id']]['negated']
        for day in q['targets']:
            day['target'] = 1 - float(day['target']) # flip the forecast probabilities
        if q['answers'][0] == 'yes':
            negated_q['answers'] = ['no']
        else:
            negated_q['answers'] = ['yes']
        all_questions.append(negated_q)
        
    all_questions.append(q)
```

This part is for modifying the values of `negated_q` from the original `q`.

However, the current code flips the probability of the original, not the negated one:

```
for day in q['targets']:
    day['target'] = 1 - float(day['target']) # flip the forecast probabilities
```        
Hence, I think that it should be modified as follow:

```
for day in negated_q['targets']:
    day['target'] = 1 - float(day['target']) # flip the forecast probabilities
```        

Do I miss something, or is the suggested modification right? 

Thanks.

**Comment by andyzoujm** [comment]
Thanks for catching this. (Note that this blurb of code was written after the experiments so the reported results are still valid.)
