### ISSUE TITLE
Availability of downloaded cc_news 

### ISSUE THREAD

**Issue by bbuing9** [andyzoujm/autocast#2]
Hi, I'm trying to download news articles from a common crawl with the specified period in the paper (2016 to mid-2022), 
but it is recursively failing by being stuck with some articles. 

Also, as a new download from CC could make the difference in retrieval source, it would be really helpful for reproducibility l if the authors provide the used source articles (>200GB).

Is there any plan or way to provide the used source articles with an external link or drive?  

Thank you very much!

**Comment by andyzoujm** [comment]
Hi, the news corpus can be downloaded [here](https://drive.google.com/file/d/1-9bK_3fl41GyCeMrzfneItu5VT0Qx0rZ/view).
