### ISSUE TITLE
How to make inference on the test set with FiD Temporal?

### ISSUE THREAD

**Issue by Ravoxsg** [andyzoujm/autocast#3]
Hi,
Thanks for sharing the great work!

I have a question regarding inference usage of the FiD Temporal model. In the paper, it says "_For each day between the question’s open and close date, we generate an embedding of the top news article using the frozen fine-tuned FiD Static model. These embeddings are then treated as input embeddings to an autoregressive model (GPT-2 (Radford et al., 2019)), which is fine-tuned to predict the average of the daily crowd prediction and the ground truth outcome._"  As far as I know, at test time, only the publishing date and the closing date are known. Then, how to apply FiD Temporal? Do you retrieve 10 articles / day throughout the entire time period, and make a prediction every day, then aggregate (average? max-pool?) predictions? Or just use the day before the closing date (which would make sense according to Figure 6)?

**Comment by andyzoujm** [comment]
With the Temporal model we do get a prediction every day, but we discard them and only use the prediction on the day before closing.

**Comment by Ravoxsg** [comment]
Ok, thanks a lot for clarifying!
